masterclass_admin_index:
    path: master-class
    methods: [GET]
    defaults:
        _controller: 'MasterClass\Controller\Admin\ProductController::indexAction'
        _legacy_controller: 'AdminMasterIndexClass'
        _legacy_link: AdminMasterIndexClass

masterclass_admin_products:
    path: master-class/products
    methods: [GET]
    defaults:
        _controller: 'MasterClass\Controller\Admin\ProductController::listingAction'
        _legacy_controller: 'AdminMasterListingClass'
        _legacy_link: AdminMasterListingClass

masterclass_admin_products_search:
    path: master-class/products
    methods: [POST]
    defaults:
        _controller: 'MasterClass\Controller\Admin\ProductController::listingSearchAction'
